const facts = [
    { id: 1, text: "My random fact is that I have two brothers." },
    { id: 2, text: "My fav color is purple." },
    { id: 3, text: "I like to swim." },
    { id: 4, text: "I broke my finger." },
    { id: 5, text: "My name is Victor, and I'm ambidextrous." },
    { id: 6, text: "I can say my alphabet backwards." },
    { id: 7, text: "I am not famous." },
    { id: 8, text: "I was born in Louisiana." },
    { id: 9, text: "I have never had a Peanut Butter and Jelly Sandwich!" },
    { id: 10, text: "I am allergic to cats." },
    { id: 11, text: "I like trains." },
    { id: 12, text: "I know the secret identity of beastcarp1." },
    { id: 13, text: "I have a dog." },
    { id: 14, text: "I hate UNA parking." },
    { id: 15, text: "I have 3 dogs." },
    { id: 16, text: "I'm adopted from China." },
    { id: 17, text: "I used to have an orange Hummer H3." },
    { id: 18, text: "I play on the rugby team." },
    { id: 19, text: "UNA basketball sold the bag." },
    { id: 20, text: "The Great Wall of China is 13,000 miles long." },
    { id: 21, text: "I hate javascript." },
    { id: 22, text: "I love the Bible verse Romans 5:8!" },
    { id: 23, text: "I love running." },
    { id: 24, text: "I have eaten 1 pound of ground beef every day for the last 6 months." },
    { id: 25, text: "Still very less parking space in UNA." },
    { id: 26, text: "I enjoy kickboxing." }
  ];
  